### ISSUE TITLE
Block dimming from a certain level

### ISSUE THREAD

**Issue by madmanxxx** [HalosGhost/enlighten#10]
Such command line switch would be very useful in a scenario where enlighten is executed on pressing dedicated Fn+ function key. I use it this way with a step configured to 5% and the problem in my case is that brightness below 15 % is already too dark and makes the screen unreadable, so it makes no sense to dim it further.

**Comment by HalosGhost** [comment]
This is a good idea.

Min and Max thresholds are a totally reasonable feature to add.

This will probably take the form of two more environment variables (preliminarily, ``BACKLIGHT_MIN`` and ``BACKLIGHT_MAX``) that you can export ahead of time (just as you can export ``BACKLIGHT_DEVICE``). We can also probably keep some of our same parsing so that you can set percentage thresholds rather than just absolute steps.

**Comment by HalosGhost** [comment]
preliminarily implemented in https://github.com/HalosGhost/enlighten/commit/a86b3b6f2f48ac3ff2324b5c003846feb84ccbcf
