### ISSUE TITLE
Add transition so jumps in brightness are gradual instead of abrupt

### ISSUE THREAD

**Issue by meskarune** [HalosGhost/enlighten#11]
Add a transition to jumps in brightness. Basically what it says on the tin. Two reasons, I think people actually expect this behaviour, and It reduces eye strain

Some ideas on implementation:

1. universally take 10 steps between current and target, and increment by 10 percent of the difference between the current and the target
2. Use percentages. If you are going from 30% brightness to 82% brightness you can transition by 5% until you are close and then jump to the remainder.

**Comment by HalosGhost** [comment]
This is definitely an interesting idea.

There are some obvious things I can do to make the implementation easy. The basic algorithm could work something like this:

* take the absolute value of the difference between current and target brightnesses (``|cur - tar|``)
* divide the difference above by 10: (``diff / 10``)
* ten times, write an accumulation of the steps (``for (i = cur + step; i < tar; i += step) { write_brightness(i); }``)

Some things to consider:

* doing this portably almost certainly requires floating point arithmetic (or, I suppose I could implement rationals or something, but implementing a new number type for this seems a touch overkill). We've tried to avoid floating-point for accuracy's sake for a long time, so this would be a surrender on that point.
* how long should we pause between each step? ``enlighten`` is very fast (mostly because it's not doing a huge amount of work); if we have no pause, it might not even be noticeable that it's transitioning at all.
* are ten steps enough? if the magnitude of change is greater, should there be more steps so that the transition is smoother, or the same so the time of the transition is constant?

I'd be very interested to hear your thoughts on these points of consideration.

Finally, just to have for the record, it is very easy to script enlighten to do this behavior with shell. There's no reason this functionality cannot be built-in (other than that there may be some strong opinions out there about the above questions and it may be difficult to bake-in the configurability for all of the possible variations), but scripting might offer greater flexibility for people to configure it the way they want.

Please let me know what you think!

**Comment by CameronNemo** [comment]
FWIW I have implemented this in my project brillo. A few snags I noticed:

 * I had to flush the write buffer otherwise my brightness would not actually change until the file handle was closed
 * the write itself took some time, so I accounted for that by calling clock_gettime before and after

**Comment by HalosGhost** [comment]
In this case, it is done via repeated calls to `bl_set()` which opens and closes its own file descriptor. I have not run into buffer flushing issues when testing this. Have you? If so, please do open an issue and I can add explicit flushing if need be.

What do you mean by accounting for that time? This feature allows for people to specify how long they wish for the transition to take.
