### ISSUE TITLE
Pass device name through command line

### ISSUE THREAD

**Issue by madmanxxx** [HalosGhost/enlighten#9]
Title says all. Sometimes it's difficult to pass an environment variable...

**Comment by HalosGhost** [comment]
I fully understand why this would be preferable to env variables (though, it should be remembered that env variables have the benefit of being exportable in all typical shell environments).

The only reason it has not been added yet is because ``enlighten`` has had the aim of remaining as simple as possible, so it doesn't take any option arguments. ``h`` and ``l`` are special cases that cannot be passed with any other argument. I will have to think about whether or not this is something I want ``enlighten`` to do. (To be fair, this is not actually a huge amount of complexity, it's just more than we have now.)

**Comment by HalosGhost** [comment]
@madmanxxx, can you offer some more clarification here? When is it hard to pass environment variables?

I'm quite in-favor of usability improvements, so if I can understand where this would be a significant improvement in ergonomics, I'll gladly move forward with it.

**Comment by madmanxxx** [comment]
In my case it's LXDE configuration file; It's where you put what should be executed upon keystroke.
Source: https://wiki.lxde.org/en/LXDE:Questions#Change_hotkeys

**Comment by HalosGhost** [comment]
Is there a reason you cannot export the environment variables in [xprofile](https://wiki.archlinux.org/index.php/Xprofile)?

**Comment by madmanxxx** [comment]
Besides containing stuff in one place - none. Nevertheless it's a strong argument. Imagine a day I need to change these variables in the far future - there are actually many places they can be set, not to mention that all those places change in time due to architecture improvements, which can result in enlighten not working suddenly...

**Comment by HalosGhost** [comment]
To me, that's a better argument in favor of enlighten having a configuration system rather than doing the config at runtime through a non-standard system.

In your case specifically, you seem to want to have the things set and stay set nearly indefinitely. Would compile-time configuration be reasonable for your case (e.g., options for ``./configure`` like there is for the default device specifier), or are you depending on a binary packaging of enlighten?

**Comment by HalosGhost** [comment]
Would a config file be a reasonable solution?

**Comment by HalosGhost** [comment]
Okay, I think I finally have a solution to this. Much in the style of ``make``, I can have ``enlighten`` support passing environment variable assignments as arguments rather than actually reading from the environment.

These definitions will still look the same (though be on the right side of the command invocation rather than the left), but have the benefit that they do not rely on the environment itself; and will over-ride any env variables set that we would otherwise take as configuration.

I am also planning on this being the final feature added before cutting a 1.0 release.

**Comment by madmanxxx** [comment]
Sorry for lack of replies recently...
Compile-time path is a terrible idea, because the path might change on some kernel update or even on reboot (if someone has more than one backlight sysfs).
Back to the actual parsing: Would using [`getopt`](https://www.gnu.org/software/libc/manual/html_node/Getopt.html#Getopt) really destroy `enlighten`'s simplicity?

**Comment by HalosGhost** [comment]
@madmanxxx, would it totally blow it away? no. Is it going to be a bit of an extra pain (even for users)? yes.

For example, if you want to relatively decrease the brightness, you do the following: ``enlighten -75``. With ``getopt``, that would be read as ``-7 -5``. So, I would either need to do some interesting acrobatics to avoid parsing any digit argument (which, to be clear, could be done) and then manually find and parse that argument, or require users to pass ``--`` before the actual brightness change (which would only be necessary for relatively decreasing the brightness, not relative increasing): ``enlighten -- -75``.

Personally, I find that usage really awful, whereas allowing env declarations in the argument list doesn't negatively affect any user that is using ``enlighten`` on the cli (because you already have access to env vars), but allows anyone putting the config in a place where the environment can't be affected easily to do the configuration just as simply.

In my opinion, this sounds like it balances the use-cases pretty well. What do you think? Does this sound incorrect?

**Comment by HalosGhost** [comment]
@madmanxxx, can you offer any more thoughts on this issue?

**Comment by madmanxxx** [comment]
Well... Current argument parsing is IMHO a dead end. The only other option I see is to create a symlink to the executable (let's say enlighten2 -> enlighten), which would appear as a new version. A simple logic would check how the executable was launched and then act accordingly. This also enforces a versioning scheme :)

Also, the need to have extra command line params has lost some meaning for me, because of another behaviour - if I press "brightness up" quickly it may cause race condition and the screen goes bright and suddenly dark. Easily reproductible on heavy-loaded system. I haven't worked around this yet, but I plan to write a simple wrapper script that creates a lock file or exits if a lock file already exists. If there's a script - there are environment variables.

**Comment by HalosGhost** [comment]
I am sorry to say that I do not see any benefit in rewriting all the argument parsing (especially when that rewrite would definitely result in a far more complex interface).

And, the addition of all new parsing logic with a symlink to determine how parsing should be done is a no-go for me as well.

I think I am likely to close this issue.

However, i would appreciate it if you opened an issue regarding the bug you are experiencing with more detail. It sounds like it might be related to the smooth brightness changes I made a little while back (though, those are opt-in features).

Thank you.
